"""JWT migration compatibility and rejection of invalid credentials."""

import os
from datetime import timedelta
from types import SimpleNamespace

import jwt
import pytest
from fastapi import HTTPException

os.environ.setdefault("SECRET_KEY", "test-secret-key-not-for-production-123456")

from app.core import security

_SECRET = "dependency-migration-test-secret-123456"
# Generated by python-jose 3.5.0 before the PyJWT migration.
_LEGACY_TOKEN = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9."
    "eyJzdWIiOiJsZWdhY3ktc3R1ZGVudCIsInNpZCI6ImxlZ2FjeS1zZXNzaW9uIiwiZ2VuIjoz"
    "LCJpYXQiOjE3OTAwMDAwMDAsInNzdCI6MTc5MDAwMDAwMH0."
    "DYm10drpYsyexbGv7GT0fMCiolouWdcIV10d4sFWThU"
)


@pytest.fixture(autouse=True)
def jwt_settings(monkeypatch):
    monkeypatch.setattr(
        security,
        "settings",
        SimpleNamespace(
            secret_key=_SECRET, algorithm="HS256", access_token_expire_minutes=30
        ),
    )


def test_existing_python_jose_session_token_remains_valid():
    assert security.decode_token(_LEGACY_TOKEN) == {
        "sub": "legacy-student",
        "sid": "legacy-session",
        "gen": 3,
        "iat": 1790000000,
        "sst": 1790000000,
    }


@pytest.mark.parametrize("never_expires", [False, True])
def test_new_session_tokens_preserve_claims(never_expires):
    token = security.create_access_token(
        {"sub": "student", "sid": "session", "gen": 2},
        never_expires=never_expires,
    )
    payload = security.decode_token(token)
    assert payload["sub"] == "student"
    assert payload["sid"] == "session"
    assert payload["gen"] == 2
    assert isinstance(payload["iat"], int)
    assert payload["sst"] == payload["iat"]
    assert ("exp" in payload) is not never_expires


@pytest.mark.parametrize(
    "token",
    [
        "malformed-token",
        _LEGACY_TOKEN.rsplit(".", 1)[0] + "." + "A" * 43,
        jwt.encode({"sub": "student"}, _SECRET, algorithm="HS512"),
        jwt.encode({"sub": "student"}, "", algorithm="none"),
        jwt.encode({"sub": "student", "exp": 1}, _SECRET, algorithm="HS256"),
    ],
)
def test_invalid_tokens_return_unauthorized(token):
    with pytest.raises(HTTPException) as error:
        security.decode_token(token)
    assert error.value.status_code == 401
    assert error.value.headers == {"WWW-Authenticate": "Bearer"}


def test_expired_session_token_is_rejected():
    token = security.create_access_token(
        {"sub": "student", "sid": "session", "gen": 1},
        expires_delta=timedelta(seconds=-1),
    )
    with pytest.raises(HTTPException) as error:
        security.decode_token(token)
    assert error.value.status_code == 401
