"""Remove difficulty_level from assignment_template and lesson tables

Revision ID: 9a9b19785108
Revises: e79031345e57
Create Date: 2025-08-16 16:12:59.836799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a9b19785108'
down_revision: Union[str, None] = 'e79031345e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_templates', 'difficulty_level')
    op.drop_column('lessons', 'difficulty_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('difficulty_level', postgresql.ENUM('beginner', 'intermediate', 'advanced', name='difficultylevel'), autoincrement=False, nullable=True))
    op.add_column('assignment_templates', sa.Column('difficulty_level', postgresql.ENUM('beginner', 'intermediate', 'advanced', name='difficultylevel'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
