"""Add student points system with fixed relationships

Revision ID: e79031345e57
Revises: b092f9a3f2b8
Create Date: 2025-08-12 22:14:30.205814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79031345e57'
down_revision: Union[str, None] = 'b092f9a3f2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.String(length=500), nullable=False),
    sa.Column('setting_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.create_table('point_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_description', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_transactions_id'), 'point_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_point_transactions_student_id'), 'point_transactions', ['student_id'], unique=False)
    op.create_index(op.f('ix_point_transactions_transaction_type'), 'point_transactions', ['transaction_type'], unique=False)
    op.create_table('student_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_points_id'), 'student_points', ['id'], unique=False)
    op.create_index(op.f('ix_student_points_student_id'), 'student_points', ['student_id'], unique=True)
    
    # Insert default system settings for points system
    op.execute("""
        INSERT INTO system_settings (setting_key, setting_value, setting_type, description, is_active)
        VALUES 
        ('points_system_enabled', 'true', 'boolean', 'Enable or disable the student points/gamification system', true)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_points_student_id'), table_name='student_points')
    op.drop_index(op.f('ix_student_points_id'), table_name='student_points')
    op.drop_table('student_points')
    op.drop_index(op.f('ix_point_transactions_transaction_type'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_student_id'), table_name='point_transactions')
    op.drop_index(op.f('ix_point_transactions_id'), table_name='point_transactions')
    op.drop_table('point_transactions')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
