"""Add API keys table for external integrations

Revision ID: 83ea02f5b877
Revises: 7aa54a011e81
Create Date: 2025-08-17 20:45:10.445834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ea02f5b877'
down_revision: Union[str, None] = '7aa54a011e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.drop_index('idx_assignment_templates_subject_id', table_name='assignment_templates')
    op.drop_index('idx_attendance_records_student_date', table_name='attendance_records')
    op.drop_index('idx_student_assignments_student_assigned_date', table_name='student_assignments')
    op.drop_index('idx_student_assignments_student_graded_date', table_name='student_assignments')
    op.drop_index('idx_terms_academic_year_start_date', table_name='terms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_terms_academic_year_start_date', 'terms', ['academic_year', 'start_date'], unique=False)
    op.create_index('idx_student_assignments_student_graded_date', 'student_assignments', ['student_id', 'graded_date'], unique=False)
    op.create_index('idx_student_assignments_student_assigned_date', 'student_assignments', ['student_id', 'assigned_date'], unique=False)
    op.create_index('idx_attendance_records_student_date', 'attendance_records', ['student_id', 'date'], unique=False)
    op.create_index('idx_assignment_templates_subject_id', 'assignment_templates', ['subject_id'], unique=False)
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
