import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach, expect, it, vi } from 'vitest'
import LessonPlanning from './LessonPlanning'
import type { Lesson } from '../types/lesson'

const mocks = vi.hoisted(() => ({ list: vi.fn(), impact: vi.fn(), batch: vi.fn(), toast: vi.fn() }))
vi.mock('../contexts/AuthContext', async original => ({ ...await original<typeof import('../contexts/AuthContext')>(), useAuth: () => ({user:{id:1,role:'admin'}}) }))
vi.mock('../components/ui', async original => ({...await original<typeof import('../components/ui')>(), useToast:()=>({toast:mocks.toast})}))
vi.mock('../components/lessons/LessonBoard', () => ({ default:()=>null }))
vi.mock('../components/lessons/PlannerHeader', () => ({ default:()=>null }))
vi.mock('../services/lessons', () => ({lessonsApi:{list:mocks.list,impact:mocks.impact,batch:mocks.batch,drawer:vi.fn().mockResolvedValue([]),rollover:vi.fn().mockResolvedValue({lessons:[],warnings:[],moved_count:0})}}))
vi.mock('../services/subjects',()=>({subjectsApi:{getAll:vi.fn().mockResolvedValue([])}}))
vi.mock('../services/assignments',()=>({assignmentsApi:{getStudents:vi.fn().mockResolvedValue([{id:2,first_name:'William',last_name:'Ashley'}])}}))
vi.mock('../services/settings',()=>({settingsApi:{getGroupedSettings:vi.fn().mockResolvedValue({attendance:{skip_weekends:false}})}}))
vi.mock('../services/api',()=>({api:{get:vi.fn().mockResolvedValue({name:'Family school'})},getErrorMessage:()=> 'Try again.'}))
vi.mock('../hooks/useLessons',()=>({useLessons:()=>({lessons:[],loading:false,error:null,refetch:vi.fn(),toggleMaterial:vi.fn()})}))
const makeLesson=(id:number,date:string,title:string):Lesson=>({id,date,title,position:0,status:'planned',students:[],templates:[],materials:[],resources:[],paperless_materials:[],external_id:`lesson-${id}`,created_at:'',updated_at:''})
const week=[makeLesson(1,'2026-10-05','Monday reading'),makeLesson(2,'2026-10-11','Sunday nature walk')]
beforeEach(()=>{
  vi.clearAllMocks()
  localStorage.clear()
  localStorage.setItem('lessonPlanning.daysShown','5')
  mocks.list.mockResolvedValue(week)
  mocks.impact.mockResolvedValue([])
  mocks.batch.mockResolvedValue(week.map(lesson=>({lesson,warnings:[]})))
})
const open=()=>render(<MemoryRouter initialEntries={['/lessons?date=2026-10-05']}><LessonPlanning/></MemoryRouter>)
it('starts collapsed, skips hidden controls when tabbing, and supports keyboard expansion',async()=>{
  const user = userEvent.setup()
  const view = open()
  const toggle = screen.getByRole('button',{name:'More Plan Controls'})
  expect(toggle).toHaveAttribute('aria-expanded','false')
  expect(document.getElementById(toggle.getAttribute('aria-controls')!)).not.toBeVisible()
  expect(screen.queryByRole('button',{name:'Print week'})).not.toBeInTheDocument()
  expect(screen.getByLabelText('Copy starting on')).not.toBeVisible()

  toggle.focus()
  await user.tab()
  expect(document.body).toHaveFocus()
  toggle.focus()
  await user.keyboard('{Enter}')
  expect(toggle).toHaveAttribute('aria-expanded','true')
  expect(screen.getByRole('button',{name:'Print week'})).toBeVisible()
  await user.tab()
  expect(screen.getByLabelText('Copy starting on')).toHaveFocus()
  toggle.focus()
  await user.keyboard(' ')
  expect(toggle).toHaveAttribute('aria-expanded','false')

  await user.click(toggle)
  view.unmount()
  open()
  expect(screen.getByRole('button',{name:'More Plan Controls'})).toHaveAttribute('aria-expanded','false')
})
it('preserves the copy date and selected students when collapsed and reopened',async()=>{
  const user = userEvent.setup()
  open()
  const toggle = screen.getByRole('button',{name:'More Plan Controls'})
  await user.click(toggle)
  const date = screen.getByLabelText('Copy starting on')
  fireEvent.change(date,{target:{value:'2026-10-19'}})
  await user.click(screen.getByText('Students for copies · same as original'))
  await user.click(await screen.findByRole('checkbox',{name:'William'}))
  await user.click(toggle)
  expect(date).not.toBeVisible()
  await user.click(toggle)
  expect(screen.getByLabelText('Copy starting on')).toHaveValue('2026-10-19')
  expect(screen.getByRole('checkbox',{name:'William'})).toBeChecked()
  await user.click(screen.getByRole('button',{name:'Copy week'}))
  await screen.findByText('No assignments affected.')
  await user.click(screen.getByRole('button',{name:'Apply changes'}))
  await waitFor(()=>expect(mocks.batch).toHaveBeenCalledWith([1,2],'copy','2026-10-19',[2]))
  expect(toggle).toHaveAttribute('aria-expanded','true')
})
it('prints the full selected week even when the five-day board has no loaded lessons',async()=>{
  open()
  await userEvent.click(screen.getByRole('button',{name:'More Plan Controls'}))
  await userEvent.click(screen.getByRole('button',{name:'Print week'}))
  expect(await screen.findByText('Sunday nature walk')).toBeInTheDocument()
  expect(mocks.list).toHaveBeenCalledWith({start_date:'2026-10-05',end_date:'2026-10-11'})
  expect(screen.getByText('Family school · Learning plan')).toBeInTheDocument()
})
it('copies the full week after reviewing its new work, independent of board width',async()=>{
  open()
  await userEvent.click(screen.getByRole('button',{name:'More Plan Controls'}))
  await userEvent.click(screen.getByRole('button',{name:'Copy week'}))
  await screen.findByText('No assignments affected.')
  await userEvent.click(screen.getByRole('button',{name:'Apply changes'}))
  await waitFor(()=>expect(mocks.batch).toHaveBeenCalledWith([1,2],'copy','2026-10-12',undefined))
})
